version: "3.5"

services:
  plugin:
    container_name: plugin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/plugin"
      - "/plugin/node_modules"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HTTPS=true